### ISSUE TITLE
add c++ codes 

### ISSUE THREAD

**Issue by markandey007** [markandey007/hacktoberfest_2022#2]

**Comment by abhishekSharmaGithub** [comment]
i can do this

**Comment by abhishekSharmaGithub** [comment]
#include "bits/stdc++.h"
using namespace std;
int main()
{
    ios::sync_with_stdio(0);
    cin.tie(0);
    int t;
    cin>>t;
    int q=0;
    while(t--){
        q++;
        int n;
        cin>>n;
        vector<pair<string,int>> v;
        vector<pair<int,int>>v1;
        for(int i=0;i<n;i++){
        string s;
        cin>>s;
        int c,id;
        cin>>c>>id;
            v.push_back({s,id});
            v1.push_back({c,id});
        }
        sort(v.begin(),v.end());
        sort(v1.begin(),v1.end());
        int ans=0;
        for(int i=0;i<n;i++){
            if(v[i].second==v1[i].second){
                ans++;
            }
        }
        cout<<"Case #"<<q<<": "<<ans<<endl;

    }
    return 0;
}
