### ISSUE TITLE
N queen problem

### ISSUE THREAD

**Issue by Djsmk123** [markandey007/hacktoberfest_2022#94]
Want to add N queen problem in C++

**Comment by pnaskardev** [comment]
Please assign me this problem

**Comment by anshu-6537** [comment]
Assign me this problem..pleasee

**Comment by vaibhav23agrawal** [comment]
Hey sir, can you please assign me this issue...

**Comment by teenu19012287** [comment]
Hello sir, please assign this issue to me .I will do this code efficiently  and in optimized way in Cpp
